from __future__ import annotations

from bi_agent.runtime.capability_models import CapabilityCard


_CATALOG: dict[str, CapabilityCard] = {
    capability_id: CapabilityCard(
        capability_id=capability_id,
        business_name=business_name,
        description=description,
        input_schema={
            "metric": "metric_id",
            "scope": "business_scope",
            "time_window": "time_window",
        },
        output_schema={
            "evidence_ref": "string",
            "typed_payload": "object",
            "limitations": "list",
        },
        supported_question_families=question_families,
        supported_grains=("day", "week", "month"),
        allowed_claim_types=claim_types,
        default_evidence_type=evidence_type,
        cost_tier=cost_tier,
        runtime_tier=runtime_tier,
        preconditions=("metric_contract_active", "aggregate_permission_allowed"),
        failure_modes=("coverage_gap", "unsupported_grain", "missing_contract"),
    )
    for (
        capability_id,
        business_name,
        description,
        question_families,
        claim_types,
        evidence_type,
        cost_tier,
        runtime_tier,
    ) in (
        (
            "metric_coverage_profile",
            "指标覆盖检查",
            "Check metric coverage for the requested scope and grain.",
            ("data_quality_or_evidence_review",),
            ("contract_coverage_and_trust_boundary",),
            "insufficient",
            "low",
            "short",
        ),
        (
            "metric_timeseries",
            "指标时间序列",
            "Build an aggregate time series for a metric.",
            ("pattern_explanation", "paid_amount_change_explanation"),
            ("comparative_change", "recurring_pattern_existence"),
            "statistical_association",
            "low",
            "short",
        ),
        (
            "data_quality_profile",
            "数据质量检查",
            "Review data trust boundaries and limitations.",
            (
                "data_quality_or_evidence_review",
                "pattern_explanation",
                "custom_baseline_comparison",
                "paid_amount_change_explanation",
            ),
            ("contract_coverage_and_trust_boundary",),
            "insufficient",
            "low",
            "short",
        ),
        (
            "compare_periods",
            "周期对比",
            "Compare target and baseline periods for a metric.",
            (
                "custom_baseline_comparison",
                "pattern_explanation",
                "paid_amount_change_explanation",
            ),
            ("comparative_change", "baseline_stability"),
            "statistical_association",
            "low",
            "short",
        ),
        (
            "compare_period_phases",
            "周期内阶段对比",
            "Compare phases inside a period.",
            ("pattern_explanation",),
            ("recurring_pattern_existence",),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "rolling_window_compare",
            "滚动窗口对比",
            "Compare rolling windows and sustained movement.",
            ("pattern_explanation", "paid_amount_change_explanation"),
            ("baseline_stability", "comparative_change"),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "weekday_calendar_compare",
            "星期日历对比",
            "Compare weekday or calendar buckets.",
            ("pattern_explanation",),
            ("recurring_pattern_existence",),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "event_window_compare",
            "事件窗口对比",
            "Compare metric movement around a known event or assumption.",
            ("business_object_impact_review", "pattern_explanation"),
            ("business_object_candidate_impact", "candidate_mechanism"),
            "candidate_mechanism",
            "medium",
            "normal",
        ),
        (
            "formula_decompose",
            "公式拆解",
            "Decompose a metric into available formula components.",
            ("paid_amount_change_explanation", "revenue_health_review"),
            ("formula_component_contribution",),
            "accounting_contribution",
            "medium",
            "normal",
        ),
        (
            "component_contribution",
            "组件贡献",
            "Quantify component contribution between periods.",
            ("paid_amount_change_explanation", "revenue_health_review"),
            ("formula_component_contribution",),
            "accounting_contribution",
            "medium",
            "normal",
        ),
        (
            "driver_decomposition",
            "驱动拆解",
            "Decompose paid amount movement into volume and unit-value drivers.",
            (
                "segment_or_factor_attribution",
                "paid_amount_change_explanation",
                "revenue_health_review",
                "custom_baseline_comparison",
            ),
            ("formula_component_contribution",),
            "accounting_contribution",
            "medium",
            "normal",
        ),
        (
            "segment_contribution",
            "渠道或分群贡献",
            "Compare target and baseline by segment and rank positive or negative contribution.",
            ("segment_or_factor_attribution", "paid_amount_change_explanation"),
            ("segment_contribution_or_mix_shift",),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "segment_breakdown",
            "分群拆解",
            "Break down metric values across one dimension.",
            ("segment_or_factor_attribution", "paid_amount_change_explanation"),
            ("segment_contribution_or_mix_shift",),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "segment_shift_compare",
            "分群结构变化",
            "Compare segment mix between baseline and target.",
            ("segment_or_factor_attribution", "paid_amount_change_explanation"),
            ("segment_contribution_or_mix_shift",),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "candidate_dimension_screen",
            "候选维度筛选",
            "Rank eligible dimensions before deeper attribution.",
            ("segment_or_factor_attribution", "pattern_explanation"),
            ("segment_contribution_or_mix_shift",),
            "statistical_association",
            "high",
            "long",
        ),
        (
            "joint_attribution",
            "组合归因",
            "Test selected dimension combinations.",
            ("segment_or_factor_attribution", "paid_amount_change_explanation"),
            ("geo_device_combination_attribution", "segment_contribution_or_mix_shift"),
            "statistical_association",
            "high",
            "long",
        ),
        (
            "outlier_scan",
            "异常周期检查",
            "Find anomalous periods or segments that affect a claim.",
            ("anomaly_or_black_swan_review", "pattern_explanation"),
            ("external_shock_candidate_or_anomaly", "payment_chain_risk_or_anomaly"),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "outlier_contribution",
            "异常贡献",
            "Estimate whether a period-level change is concentrated in a few high-impact periods.",
            ("anomaly_or_black_swan_review", "paid_amount_change_explanation"),
            ("external_shock_candidate_or_anomaly", "comparative_change"),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "change_point_scan",
            "变化点检查",
            "Detect candidate breakpoints in a metric series.",
            ("anomaly_or_black_swan_review", "paid_amount_change_explanation"),
            ("external_shock_candidate_or_anomaly", "comparative_change"),
            "statistical_association",
            "medium",
            "normal",
        ),
        (
            "evidence_reduce",
            "证据整理",
            "Merge compatible evidence into a claim-ready summary.",
            (
                "pattern_explanation",
                "paid_amount_change_explanation",
                "segment_or_factor_attribution",
                "custom_baseline_comparison",
            ),
            ("comparative_change", "recurring_pattern_existence"),
            "insufficient",
            "low",
            "short",
        ),
        (
            "answer_verify",
            "答案校验",
            "Verify final claims against evidence and contracts.",
            (
                "data_quality_or_evidence_review",
                "pattern_explanation",
                "paid_amount_change_explanation",
                "segment_or_factor_attribution",
                "custom_baseline_comparison",
            ),
            ("contract_coverage_and_trust_boundary", "comparative_change"),
            "insufficient",
            "low",
            "short",
        ),
    )
}


def public_capability_ids() -> tuple[str, ...]:
    return tuple(_CATALOG)


def get_capability_card(capability_id: str) -> CapabilityCard:
    return _CATALOG[capability_id]


def llm_capability_cards() -> list[dict]:
    return [card.to_llm_summary() for card in _CATALOG.values()]
